### ISSUE TITLE
New Paper (Other): Discovery of a novel coronavirus associated with the recent pneumonia outbreak in humans and its potential bat origin

### ISSUE THREAD

**Issue by ajlee21** [greenelab/covid19-review#165] opened 2020-04-07 20:31 UTC
Title: Discovery of a novel coronavirus associated with the recent pneumonia outbreak in humans and its potential bat origin

# General Information
## Please paste a link to the paper or a citation here:

https://www.biorxiv.org/content/10.1101/2020.01.22.914952v1

## What is the paper's [Manubot-style citation](https://github.com/greenelab/covid19-review/blob/master/USAGE.md#citations)?

Citation: doi:10.1038/s41586-020-2012-7

### Is this paper primarily relevant to Background or Pathogenesis? 

- [x] Background
- [ ] Pathogenesis
- [ ] Methods

## Please list some keywords (3-10) that help identify the relevance of this paper to COVID-19

* keyword 1 (replace me, copy and paste more than three if needed)
* keyword 2 (replace me, copy and paste more than three if needed)
* keyword 3 (replace me, copy and paste more than three if needed)

## Which areas of expertise are particularly relevant to the paper?

- [x] virology
- [ ] epidemiology
- [ ] biostatistics
- [ ] immunology
- [ ] pharmacology
- [ ] other:

# Summary

### Suggested questions to answer about each paper:
- What did they analyze?
- What methods did they use?
- Does this paper study COVID-19, SARS-CoV-2, or a related disease and/or virus?
- What is the main finding (or a few main takeaways)?
- What does this paper tell us about the background and/or diagnostics/therapeutics for COVID-19 / SARS-CoV-2?
- Do you have any concerns about methodology or the interpretation of these results beyond this analysis?

### Any comments or notes?

Paper looks at the origin of SARS-CoV2
@johnbarton mentioned he might be interested in adding to this section

**Comment by rdvelazquez** [comment] 2020-04-23 14:52
This is a duplicate of #106

**Closed by rdvelazquez** 2020-04-23 14:52 UTC
Labels: New Paper, Review Needed, duplicate, virology
